name: Provision Azure Infrastructure Resources

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  DeployInfra:
    runs-on: ubuntu-latest
    environment: Dev
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_USE_OIDC: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: latest

      - name: Azure login
        uses: azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform init
        id: init
        run: |
          set -a 
          source .env.backend
          terraform init \
            -backend-config="resource_group_name=$TF_VAR_state_resource_group_name" \
            -backend-config="storage_account_name=$TF_VAR_state_storage_account_name"

      - name: Validate Terraform Code
        working-directory: ./terraform/dev
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform/dev
        run: terraform plan

      - name: Apply FIC Configuration
        working-directory: ./terraform/dev
        run: terraform apply -auto-approve
