name: Destroy gh secret

on:
  workflow_run:
    workflows: ["Setup Federated Identity Credential"]
    types:
      - completed

permissions:
  contents: read
  actions: write

jobs:
  DestroySecret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Delete Secret Using GitHub CLI API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api --method DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/HemSarz/Kubernetes/environments/Dev/secrets/AZURE_CLIENT_SECRET