name: Setup Federated Identity Credential
'on':
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
jobs:
  DeployOIDC:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: latest

      - name: Az login
        uses: azure/login@v2.2.0
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
          
      - name: Create PLAN Directory
        run: mkdir -p ./terraform/dev/plans

      - name: Initialize Terraform
        working-directory: ./terraform/dev
        run: terraform init

      - name: Validate Terraform Code
        working-directory: ./terraform/dev
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform/dev
        run: terraform plan -out=./plans/plan.tfplan | tee ./plans/plan_output.txt

      - name: Debug Plan Files
        run: ls -al ./terraform/dev/plans

      - name: Plan Summary
        uses: sgametrio/terraform-summary-action@main
        with:
          log-file: ./terraform/dev/plans/plan_output.txt
          title: "Terraform Plan Summary" 

      - name: Apply FIC Configuration
        working-directory: ./terraform/dev
        run: terraform apply -auto-approve ./plans/plan.tfplan
