name: Deploy Federated Identity Credentials

on:
  workflow_dispatch:

jobs:
  setup-fic:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.10.1

    - name: Azure login
      uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'



    - name: Initialize Terraform
      working-directory: ./terraform/fic
      run: terraform init

    - name: Validate Terraform Code
      working-directory: ./terraform/fic
      run: terraform validate

    - name: Terraform Plan
      working-directory: ./terraform/fic
      run: terraform plan

    - name: Apply FIC Configuration
      working-directory: ./terraform/fic
      run: terraform apply -auto-approve