name: Deploy Federated Identity Credential
on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'The environment name'
        required: true
        default: 'Dev'

permissions:
  id-token: write
  contents: read
  actions: write

jobs:
  setup-fic:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment_name }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.10.1

    - name: Authenticate with Azure
      run: |
        az login --service-principal \
        -u ${{ secrets.ARM_CLIENT_ID }} \
        -p ${{ secrets.ARM_CLIENT_SECRET }} \
        --tenant ${{ secrets.ARM_TENANT_ID }}

    - name: Initialize Terraform
      working-directory: ./terraform/fic
      run: terraform init

    - name: Validate Terraform Code
      working-directory: ./terraform/fic
      run: terraform validate

    - name: Terraform Plan
      working-directory: ./terraform/fic
      run: terraform plan

    - name: Apply FIC Configuration
      working-directory: ./terraform/fic
      run: terraform apply -auto-approve

    - name: Remove ARM_CLIENT_SECRET using GitHub CLI API
      run: |
        gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
        gh api --method DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/environments/${{ github.event.inputs.environment_name }}/secrets/ARM_CLIENT_SECRET
