name: Setup Federated Identity Credential

on:
  workflow_dispatch:

jobs:
  DeployOIDC:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: latest

      - name: Az login
        uses: azure/login@v2.2.0
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Verify WorkingDir
        run: pwd && ls -al ./terraform/fic

      - name: GH Identity
        run: |
          git config --global user.email "${{ secrets.GHUSEREMAIL }}"
          git config --global user.name "${{ secrets.GHUSER }}"

      - name: Create PLAN Directory
        run: |
          if [ ! -d "./terraform/fic/plans" ]; then
            mkdir -p ./terraform/fic/plans && touch ./terraform/fic/plans/.gitkeep
            git add ./terraform/fic/plans/.gitkeep
            git commit -m "Create PLAN Directory" && git push
          fi

      - name: Verify Plan Directory
        run: ls -al ./terraform/fic/plans

      - name: Generate Plan Name
        id: generate_plan_name
        run: |
          PLAN_NAME=$(TZ=Europe/Oslo date +%Y-%m-%d_%H-%M-%S)
          echo "PLAN_NAME=$PLAN_NAME" >> $GITHUB_OUTPUT
        shell: bash

      - name: Build Plan File Path
        id: build_plan_path
        run: echo "PLAN_FILE_PATH=./terraform/fic/plans/${{ steps.generate_plan_name.outputs.PLAN_NAME }}.tfplan" >> $GITHUB_OUTPUT
        shell: bash

      - name: Initialize Terraform
        working-directory: ./terraform/fic
        run: terraform init

      - name: Validate Terraform Code
        working-directory: ./terraform/fic
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform/fic
        run: terraform plan -out=${{ steps.build_plan_path.outputs.PLAN_FILE_PATH }} | tee ./terraform/fic/plans/plan_output.txt

      - name: Commit and Push Plan Files
        working-directory: ./terraform/fic
        run: |
          git add ./plans/plan_output.txt
          git add ${{ steps.build_plan_path.outputs.PLAN_FILE_PATH }}
          git commit -m "Add Terraform Plan ${{ steps.generate_plan_name.outputs.PLAN_NAME }}" || true
          git push origin main || true

      - name: Verify Plan Directory
        working-directory: ./terraform/fic
        run: ls -al ./terraform/fic/plans

      - name: Plan Summary
        uses: sgametrio/terraform-summary-action@main
        with:
          log-file: ./terraform/fic/plans/plan_output.txt
          title: "Terraform Plan Summary"

      - name: Apply FIC Configuration
        working-directory: ./terraform/fic
        run: terraform apply -auto-approve ${{ steps.build_plan_path.outputs.PLAN_FILE_PATH }}