name: Deploy Federated Identity Credential

on:
  workflow_dispatch:

jobs:
  setup-fic:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3.1.2
      with:
        terraform_version: 1.10.1

    - name: Authenticate with Azure
      uses: Azure/login@v2
      with:
        creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'

    - name: Initialize Terraform
      working-directory: ./terraform/fic
      run: terraform init

    - name: Validate Terraform Code
      working-directory: ./terraform/fic
      run: terraform validate

    - name: Terraform Plan
      working-directory: ./terraform/fic
      run: terraform plan

    - name: Apply FIC Configuration
      working-directory: ./terraform/fic
      run: terraform apply -auto-approve
