name: Destroy gha secret
on:
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  setup-fic:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Delete Secret Using GitHub CLI API
      run: |
        gh api --method DELETE \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        -H "Authorization: token ${{ secrets.dlsec }}" \
        /repos/hemsarz/kubernetes/environments/Dev/secrets/ARM_CLIENT_SECRET

        env:
        GH_TOKEN: ${{ github.token }}